### ISSUE TITLE
Do you plan to support other languages such as scala or clojure?

### ISSUE THREAD

**Issue by mrkaspa** [hybridgroup/artoo#154]

**Comment by hunterboerner** [comment]
There are currently two other frameworks, Gobot (http://gobot.io/) for Golang, and Cylon (http://cylonjs.com/) for JavaScript. I think Scala and Clojure were ruled out due to the JVM having trouble running on small devices, but @deadprogram would know for certain.

**Comment by deadprogram** [comment]
There is also Zorg (https://github.com/zorg-framework/zorg) in Python.

Love to see someone do this, of course.

In any case, this is somewhat off topic for Artoo itself.
