### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by splendirlabs** [hybridgroup/artoo#169]
I noticed last commits were a few years ago and Gobot seems to be very current.

Is this project still maintained or is there no more dev being done on it? Thx.

**Comment by deadprogram** [comment]
Hi @splendirlabs the bulk of our attentions are indeed focused on Gobot, but that said, Artoo still "lives".

There are a few Ruby-related updates that we will hopefully get merged in soon to Artoo and friends.

Closing... for now.
